### ISSUE TITLE
Unable to read typings for "angular2-beta-to-rc-alias"

### ISSUE THREAD

**Issue by danielcrisp** [akserg/ng2-webpack-demo#3]
- **I'm submitting a ...**
  [ x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Report a bug
- **What is the current behavior?**

`npm install` fails because of an error during the `typings install` process
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

Clone the repo.
Run `npm install`
- **What is the expected behavior?**

Install should complete successfully
- **What is the motivation / use case for changing the behavior?**

n/a
- **Please tell us about your environment:**

OSX v10.11.5
npm v3.5.3
node v.5.6.0
typings v1.3.1
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Error message:

```
typings ERR! message Unable to read typings for "angular2-beta-to-rc-alias". You should check the entry paths in "typings.d.ts" are up to date
typings ERR! caused by ENOENT: no such file or directory, open '/ng2-webpack-demo/node_modules/@angularclass/angular2-beta-to-rc-alias/src/beta-17/typings.d.ts'
```

**Comment by danielcrisp** [comment]
typings.json currently looks like this:

``` json
{
  "globalDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "core-js": "registry:dt/core-js#0.0.0+20160317120654",
    "hammerjs": "registry:dt/hammerjs#2.0.4+20160417130828",
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446",
    "node": "registry:dt/node#6.0.0+20160514165920",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654",
    "source-map": "registry:dt/source-map#0.0.0+20160317120654",
    "uglify-js": "registry:dt/uglify-js#2.6.1+20160316155526",
    "webpack": "registry:dt/webpack#1.12.9+20160321060707",
    "angular2-beta-to-rc-alias": "file:./node_modules/@angularclass/angular2-beta-to-rc-alias/src/beta-17/typings.d.ts"
  }
}
```

Is it trying to find a local file for `angular2-beta-to-rc-alias`?

**Comment by akserg** [comment]
I made a mess when played with different libraries. Now everything is fixed and tested locally.
Thank you.

**Comment by danielcrisp** [comment]
Perfect, that's fixed it - thank you
