### ISSUE TITLE
Plunker project for ng2-dnd

### ISSUE THREAD

**Issue by tonytomk** [akserg/ng2-webpack-demo#4]
If I want to create a plunker(http://plnkr.co) project for   ng2-dnd 
what is the ng2-dnd src path I have to select there is no online plugin available in plnkr for dnd ?
any help will be appreciated!!

**Comment by akserg** [comment]
I have created the project on [Plunker](http://embed.plnkr.co/JbG8Si). It is based on SystemJS. Is this suitable for you?

**Comment by tonytomk** [comment]
Hi akserg,
Yes, It's  resolved my issue!!. I was missing that mapping in the config file thank you cheers :)
